### PR TITLE
🎨 Consolidate flowchart arrow length

### PR DESCRIPTION
**Pull request by Glutexo**
All Mermaid arrows now have two dashes.

### CODE REVIEW

**Comment by nappex** [comment]
it was intention. if you writw more dash, the line is longer and flowchart looked better because certain cell move to more suitable place

**Comment by Glutexo** [comment]
```mermaid
 flowchart LR
     START             -->           operator(OPERATOR)
     operator    -- <hash>.urls --->    downloader(DOWNLOADER)
     downloader  -- <hash>.raw --->      parser(PARSER)
     parser      -- <hash>.json -->       operator
     operator           -->          MATERIALIZATION
 ```

```mermaid
 flowchart LR
     START             -->           operator(OPERATOR)
     operator    -- <hash>.urls -->    downloader(DOWNLOADER)
     downloader  -- <hash>.raw -->      parser(PARSER)
     parser      -- <hash>.json -->       operator
     operator           -->          MATERIALIZATION
 ```

**Comment by Glutexo** [comment]
If I use the triple-dash version for the “parser -> operator” line, the graph looks the same, yet the arrows are more consistent:
Triple-dash for the primary cycle,
double-dash for the input and output.

Look:

```mermaid
 flowchart LR
     START             -->           operator(OPERATOR)
     operator    -- <hash>.urls --->    downloader(DOWNLOADER)
     downloader  -- <hash>.raw --->      parser(PARSER)
     parser      -- <hash>.json --->       operator
     operator           -->          MATERIALIZATION
  ```

**Comment by Glutexo** [comment]
I updated the Pull Request with the consistent triple-dash version. Please take a fresh look and tell me what you think.

**Review by nappex — APPROVED** [review]

**Pull request merged**
