### PR TITLE
Update mix.lock after dependecies update

### PR DESCRIPTION
**Pull request by nappex**
Updated dependecies by `mix deps.update` by that command `mix.lock` changed. Before merge consider Issue #160

### CODE REVIEW

**Comment by nappex** [comment]
It seems I did not understand ~> correctly:

<p><code class="inline">~&gt;</code> will never include pre-release versions of its upper bound,
regardless of the usage of the <code class="inline">:allow_pre</code> option, or whether the operand
is a pre-release version. It can also be used to set an upper bound on only the major
version part. See the table below for <code class="inline">~&gt;</code> requirements and
their corresponding translations.</p>

~> | Translation
-- | --
~> 2.0.0 | >= 2.0.0 and < 2.1.0
~> 2.1.2 | >= 2.1.2 and < 2.2.0
~> 2.1.3-dev | >= 2.1.3-dev and < 2.2.0
~> 2.0 | >= 2.0.0 and < 3.0.0
~> 2.1 | >= 2.1.0 and < 3.0.0

**Comment by nappex** [comment]
I suggest close the PR without merge, when i run:

`$ mix deps.clean httpoison mox`
`$ mix deps.get`

The `mix.lock` haven't changed.

**Comment by Glutexo** [comment]
The lock file ensures that anybody who clones the project has the same (and assumably working) versions of the dependencies. You can always re-sync your lock file yourself if you want to upgrade. See the discussion here: https://stackoverflow.com/questions/4151495/should-gemfile-lock-be-included-in-gitignore. What do you think?

**Comment by nappex** [comment]
Probably, we solve the problem by another approach, issue related to this is #167

**Review by Glutexo — DISMISSED** [review]
The mix.lock file is ok. Re-generating it by deleting it and running the commands you suggested yields exactly the same file.

```
$ mix deps.clean httpoison mox
$ mix deps.get
```

Thus, I consider this bump valid. The tests are passing and manual run of the escript works like a charm.

**Comment by Glutexo** [comment]
@nappex Do you know how to resolve the conflict? Are you willing to do it? Or do you want to rather ditch this PR altogether? I’d prefer to merge it, since it’s easy and two smaller bumps are better than one.

**Comment by Glutexo** [comment]
I've resolved the conflict by keeping the updated versions from this pull request and also adding the new lines from the master branch for `floki` and its dependency `html_entities`. After merging, I ran `mix deps.get`, and everything installed successfully.

**Comment by nappex** [comment]
> The lock file ensures that anybody who clones the project has the same (and assumably working) versions of the dependencies. You can always re-sync your lock file yourself if you want to upgrade. See the discussion here: https://stackoverflow.com/questions/4151495/should-gemfile-lock-be-included-in-gitignore. What do you think?

**OK, I found these answers:**

**1)** https://bundler.io/guides/faq.html
Q: Should I commit my Gemfile.lock when writing a gem?

A: Yes, you should commit it. The presence of a Gemfile.lock in a gem’s repository ensures that a fresh checkout of the repository uses the exact same set of dependencies every time. We believe this makes repositories more friendly towards new and existing contributors. Ideally, anyone should be able to clone the repo, run bundle install, and have passing tests. If you don’t check in your Gemfile.lock, new contributors can get different versions of your dependencies, and run into failing tests that they don’t know how to fix.

**2)**

**Comment by nappex** [comment]
I solve the conflict @Glutexo. It should be fine, but diff is little bit strange

**Comment by nappex** [comment]
I also solve strange diff, dependecies were not in order. @Glutexo

**Review by Glutexo — APPROVED** [review]
Great job, the conflicts have been resolved and the tests are passing on my machine. Thank you for your patience, even though this work might have seemed unnecessary in the context of the related issue #167, which will overwrite these changes.

**Pull request merged**
