### PR TITLE
© Bump year in copyright

### LINKED ISSUE #98: Update copyright information
- [x] Add @nappex, #101
- [x] bump the year. #100

### PR DESCRIPTION
**Pull request by Glutexo**
It’s 2022, man!

A step to #98.

### CODE REVIEW

**Comment by Glutexo** [comment]
#100, woohoo!

**Comment by nappex** [comment]
are you planning to update the year info every year?

**Comment by Glutexo** [comment]
I do. Is there a better way? Maybe “© since 2019” or “© 2019 – now”.

**Comment by Glutexo** [comment]
[Resolved](https://github.com/Glutexo/onigumo/pull/100/commits/9c8a179ee0c4d65fe53df66a64a8f8b9bed4cf7c) conflicts.

**Review by nappex — APPROVED** [review]

**Pull request merged**
