### PR TITLE
✨ Use the first argument as a module name

### PR DESCRIPTION
**Pull request by Glutexo**
The first CLI argument with a module name enables the writing of runnable modules. A future _Parser_ module (#89) only needs a _main_ method taking the root path as an argument.

The dynamic approach also allows testing of the CLI entry point.

The approach is naïve. It does check neither the parameter count nor whether a module exists. A missing argument or an incorrect module name, including a different case, causes an uncaught error.

With the new code in place, the escript has a new invocation syntax:

```sh
$ ./onigumo Downloader
```

### CODE REVIEW

**Comment by nappex** [comment]
I've got an error:

```
$ ./onigumo Downloader
** (HTTPoison.Error) :nxdomain
    (httpoison 1.8.0) lib/httpoison.ex:156: HTTPoison.request!/5
    (onigumo 0.1.0) lib/onigumo_downloader.ex:24: Onigumo.Downloader.download_url/2
    (elixir 1.12.2) lib/stream.ex:572: anonymous fn/4 in Stream.map/2
    (elixir 1.12.2) lib/stream.ex:1559: Stream.do_element_resource/6
    (elixir 1.12.2) lib/stream.ex:1719: Enumerable.Stream.do_each/4
    (elixir 1.12.2) lib/stream.ex:649: Stream.run/1
    (elixir 1.12.2) lib/kernel/cli.ex:124: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

I invoked these commands

```
$ mix escript
$ mix escript.build
$ mix compile
```

**Comment by nappex** [comment]
Tried to find something about :nxdomain on official doc, unfortunately without success.

`nxdomain error site:https://hexdocs.pm/httpoison` -> googled

**Comment by nappex** [comment]
What is the `NXDOMAIN` error

When we try to enter a web page and we get an error message indicating NXDOMAIN, it means that the domain name could not be resolved. This logically means that we cannot navigate through that site we are trying to access.

**Comment by nappex** [comment]
I've tried to debug `HTTPoison.get!` in terminal (iex) according to tutorial on official [doc](https://hexdocs.pm/httpoison/readme.html#usage).

Unfortunately I've got an error:

```
iex(1)> HTTPoison.start()
** (UndefinedFunctionError) function HTTPoison.start/0 is undefined (module HTTPoison is not available)
    HTTPoison.start()
```

I feel helplessly... Oh no my baby woke up seize

**Comment by nappex** [comment]
If you want run
`iex(1)> HTTPoison.start()`

you have to run iex as:
`$ iex -S mix`

**Comment by nappex** [comment]
nxdomain error is something what is expected because we use as input urls with domain `onigumo.local`, that domain does not exist in reality!

**Comment by nappex** [comment]
We should consider to make special parser to parse arguments from cli to get module.

See https://elixirschool.com/en/lessons/intermediate/escripts
Then we can add more functionality to that parser, for example check numbers of args and so on.

**Review by nappex — APPROVED** [review]

**Comment by Glutexo** [comment]
I agree that using _OptionParser_ is the correct way to process the arguments. I chose to use plain pattern matching only to keep the changeset to the lowest level possible and switch to the smarter approach in the follow-up pull request.

Also the argument is rudimentary in its nature. It is a raw module name. Passing an invalid one raises an exception. That too is a sign of a temporary simplistic solution.

**Comment by Glutexo** [comment]
Thanks for your review! 🙌🏻 Merging.

**Comment by Glutexo** [comment]
Thanks for mentioning `iex -S mix`. ❤️ I was surprised that there is no mix console command and there it is!

**Pull request merged**
