### PR TITLE
♻️ Parametrize the load URL test

### LINKED ISSUE #59: Parametrize tests
Some of tests seem to be similar. For example `download a single URL` and  `download multiple URLs`.

some useful links:
- https://gist.github.com/ramalho/1fa98648737e6bb2d4d4b77a938388f7
- https://dev.to/niku/parameterized-testing-with-exunit-1j3d
- https://gist.github.com/ishikawa/2ad8c415c2a5b6a619e99c18870d6392

### PR DESCRIPTION
**Pull request by Glutexo**
The “load a single URL” and “load multiple URLs” tests were almost identical, only dealing with a different set of URLs. Parametrization reduced repetition.

To match the style in [Hash tests](https://github.com/Glutexo/onigumo/blob/6f48cd5b48b49c8cdc3756f4813faa229f34cd78/test/hash_test.exs), the _for_ clause is inside the test block.

Fixes #59.

### CODE REVIEW

**Comment by Glutexo** [comment]
I extracted (https://github.com/Glutexo/onigumo/pull/142/commits/e552c08457097534c9e1d353e818db8b12f9912d) common parts of the two iterations, revealing the flaw of having the for loop inside the test. Artifacts from the first run stay in the temporary directory, and it is just luck that it does not interfere with the second one.

**Review by nappex — DISMISSED** [review]
Nice. It is more readable and simplier...

**Comment by nappex** [comment]
I'll try to resolve conflict

**Comment by nappex** [comment]
Master merged a code is tested. Please review my merge and add to master....

**Comment by Glutexo** [comment]
I approve. ✅ Please click the “approved” button, so I can merge without _force_.

**Review by nappex — APPROVED** [review]

**Pull request merged**
